- src/api.ts
- src/server.ts
The PORT should be configurable to allow deployment on Heroku.
The default port is 3030.
In addition, the path to the samples JSON has to be relative to the start script.
The deployment is working (Certificates are in development):
https://nf-certifica-port-vm0hp3p0o5wa.herokuapp.com/?id=lmachens
> 🚀 Deploy on Heroku

- src/api.ts
- src/assets/samples/courses.json
- src/certificate.ts
Added a few lines and corrected the font colors.
> Change layout for Page 1

- src/api.ts
Had to make changes to the student fetch, due to external API changes.
> 👽️ Update fetch due to external API changes

- .env.example
- README.md
- Add `.env.example`
- Add README
> 📝 Create basic Documentation

- .github/workflows/docker-publish.yml
- Dockerfile
This workflow creates a docker image which can then be pulled to deploy the microservice
> 👷 Create Docker Workflow

- src/api.ts
- src/certificate.ts
- Create PDF even without thumbnail
- Only create third page when project is available
> 🐛 Validate JSON

- src/server.ts
This changes the default name when the file is downloaded. 
Working on Win 10 Chrome
> ✨ Change default download name of PDF

- src/certificate.ts
Fix a bug where a title would overlap everything below it
> 🐛 Adjust placement of text on third page

- README.md
- src/api.ts
Fetch the course data from a hidden gist
> 👽️ Fetch course data from gist

- src/server.ts
Add possibility to pass the course of the student via a query
> ✨ Add course query

- src/server.ts
- src/utils.ts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize
> 🚑 Replace Diacritics with normal letter

- src/api.ts
- src/assets/samples/courses.json
- src/certificate.ts
- src/server.ts
Add functionality to also get data from FS
> ✨ Get Course data from FS

- src/certificate.ts
- src/components/text.ts
For easier usage of texts and the option to set default paramerts (not implemented yet), a `text` helper is added.
> ♻️ Add text helper

- README.md
- src/api.ts
The README.md should give all the information to contribute to this project. 
Examples are added.
`COURSE_URL` is not used anymore (might be used in the future).
> 📝 Update usage guide

- src/assets/samples/courses.json
Fixed a typo in the cgn data course
> Fixed a typo in the cgn data course

- src/assets/samples/courses.json
- Added Simons second firstname and his Dr. 
- Changed the enddate from 3.8. to 10.8
- Little changes to topics
> Added Simons whole name, changed the enddate, some more little changes

- src/assets/samples/courses.json
This pr adds the `hh-web-21-4-en` course to the `courses.json` file for certificates creation.
> Add hh-web-21-4-en course to courses.json

- src/api.ts
- src/assets/dictionary/en.ts
- src/assets/samples/courses.json
- src/certificate.ts
- src/i18n.ts
Add Data Analytics and internationalization
> Add Data Analytics

- src/assets/samples/courses.json
- added analytics course info in json
> added analytics course info

- src/assets/dictionary/en.ts
- src/certificate.ts
> Fix spacing on date on first page

- src/assets/samples/courses.json
Add new course to certificate project
> 📝 Add cgn-web-21-3

- package-lock.json
- package.json
- sample.http
- src/api.ts
- src/certificate.ts
- src/schema.ts
- src/server.ts
Update server to now use express 🎉 
Refactor the createCertificate function, so it doesn't handle the response anymore.
Add new post route for non visible profiles.
Introduce schema validation for the data that is received.
> Introduce express and create post route with schema validation

- src/assets/samples/courses.json
Added the curriculum for hh-data-21-3
> Added the curriculum for hh-data-21-3

- src/assets/samples/courses.json
Added the type to the data-hh-21-3 curriculum
> added the type to the data-hh-21-3 curriculum

- src/assets/samples/courses.json
Added the hh-ds-21-4 Curriculum
> Added the hh-ds-21-4 Curriculum

- src/assets/samples/courses.json
Hey,
could you review the change please :) It's for the new 2nd page for CGN DS-3 course.
ty
Nico
> updated for latest data course

- src/assets/samples/courses.json
Added course much-analytics-21-1 to json file
> added muc-analytics-21-1 course

- src/assets/samples/courses.json
Certificate information for web-hh-21-8
> feat(web-hh-21-8): added certificate info

- src/assets/samples/courses.json
Added the hh-ds-22-1 course to the course.json
> Hh ds 22 1

- src/assets/samples/courses.json
... please review and add some fairy dust, just in case!
> updated courses JSON for hh-analytics-22-1

- package-lock.json
- src/assets/samples/courses.json
Neue Infos für den Java-22-1 Kurs
> hh-java-22-1
